import json

'''
Just fix before and after variables and run this.
'''

# To change
name=sys.argv[1]
link=sys.argv[2] #"https://hoichoihlsns.akamaized.net/vhoichoiindia2/Renditions/20211022/1634894311756_indu_ep_08_bng_rev/hls/"
before = "curl '" + link
after = "' -H 'authority: hoichoihlsns.akamaized.net' -H 'sec-ch-ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"' -H 'sec-ch-ua-mobile: ?0' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' -H 'sec-ch-ua-platform: \"Windows\"' -H 'accept: */*' -H 'origin: https://www.hoichoi.tv' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'sec-fetch-dest: empty' -H 'referer: https://www.hoichoi.tv/' -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,bn;q=0.7,hi;q=0.6,de;q=0.5,it;q=0.4' -o "

linkoutput="links_"+name      # will be generated by this script
response="response"     # contains content from the m3u3 file
outpath="files_"+name+"/"        # will be created by this script

# file to write the links
fw = open(linkoutput, "w")

# file to read the response from
f = open(response, "r")

#curl 'https://hoichoihlsns.akamaized.net/vhoichoiindia2/Renditions/20190107/1546855433067_ejcrhoichoi_converted/hls/1546855433067_ejcrhoichoi_converted_1080/00000/1546855433067_ejcrhoichoi_converted_1080_00002.ts?hdntl=exp=1568394418~acl=/*~data=hdntl~hmac=3ea0ad03e8bebbb2021f702a8f86a5b60450215e19b5aaa05d780ef06119c632' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Origin: https://www.hoichoi.tv' -H 'Connection: keep-alive' -H 'Referer: https://www.hoichoi.tv/films/title/ek-je-chhilo-raja'
# before = "curl 'https://hoichoihlsns.akamaized.net/vhoichoiindia2/Renditions/20190107/1546855433067_ejcrhoichoi_converted/hls/"
# after = "' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Origin: https://www.hoichoi.tv' -H 'Connection: keep-alive' -H 'Referer: https://www.hoichoi.tv/films/title/ek-je-chhilo-raja' -o "

fw.write("#!/bin/bash\n")
fw.write("mkdir files_"+name+"\n")

for x in f:
    if x[0] == "#":
        continue

    filename = x[0:x.index("?")]
    filename = outpath + filename[filename.rfind("/")+1:]
    fw.write(before + x[:-1] + after + filename + "\n")

fw.close()
f.close()
